name: Convert DOCX to Markdown

on:
  workflow_dispatch:
  push:
    paths:
      - '*.docx'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc -y

      - name: Convert DOCX to Markdown
        run: pandoc "RAD General Description.docx" -o "RAD-General-Description.md"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add RAD-General-Description.md
          git commit -m "Convert DOCX to Markdown" || echo "Nothing to commit"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
