      name: Process RAD Excel Files

on:
  push:
    paths:
      - '**/*.xlsx'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-rad-excel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Process RAD Excel file
        run: |
          python scripts/process_rad_excel.py

      - name: Commit and push processed CSV files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add '*.csv' || true
          git commit -m "Auto-process RAD Excel files to CSV" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}