name: Convert Files

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          python3 -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert .doc files to .md
        run: |
          for file in $(find . -type f -name "*.doc"); do
            base="${file%.doc}"
            pandoc "$file" -o "${base}.md"
          done

      - name: Convert .xlsx files to .csv for each worksheet
        run: |
          python3 - <<EOF
import os
import pandas as pd

for file in os.listdir('.'):
    if file.endswith('.xlsx'):
        excel = pd.ExcelFile(file)
        for sheet in excel.sheet_names:
            df = excel.parse(sheet)
            csv_name = f"{os.path.splitext(file)[0]}_{sheet}.csv"
            df.to_csv(csv_name, index=False)
EOF
