name: Convert Files

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          python3 -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert .doc files to .md
        run: |
          find . -type f -name "*.doc" | while read file; do
            base="${file%.doc}"
            pandoc "$file" -o "${base}.md"
          done

      - name: Convert .xlsx files to .csv for each worksheet
        run: |
          python3 <<EOF
import os
import pandas as pd

for root, dirs, files in os.walk('.'):
    for file in files:
        if file.endswith('.xlsx'):
            filepath = os.path.join(root, file)
            excel = pd.ExcelFile(filepath)
            for sheet in excel.sheet_names:
                df = excel.parse(sheet)
                # Sanitize sheet name for filename
                safe_sheet = "".join([c if c.isalnum() or c in (' ', '.', '-', '_') else '_' for c in sheet])
                csv_name = f"{os.path.splitext(filepath)[0]}_{safe_sheet}.csv"
                df.to_csv(csv_name, index=False)
EOF
