name: Convert XLSX to CSV

on:
  push:
    paths:
      - '**/*.xlsx'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert-xlsx-to-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert XLSX to CSV
        run: |
          python scripts/convert_xlsx_to_csv.py

      - name: Commit and push CSV files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add '*.csv' || true
          git commit -m "Auto-convert XLSX to CSV" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
