name: Generate DB Schema from CSVs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary eralchemy matplotlib

      - name: Generate schema and import CSVs
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: testdb
          PGPORT: 5432
        run: |
          python .github/scripts/import_csv_to_postgres.py

      - name: Dump PostgreSQL schema
        run: |
          pg_dump --schema-only --no-owner --username=postgres --host=localhost testdb > schema.sql

      - name: Upload SQL schema artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-schema
          path: schema.sql

      - name: Generate ER diagram
        run: |
          eralchemy -i "postgresql://postgres:postgres@localhost:5432/testdb" -o er_diagram.png

      - name: Upload ER diagram artifact
        uses: actions/upload-artifact@v4
        with:
          name: er-diagram
          path: er_diagram.png
